### ISSUE TITLE
在mac上64位jdk中训练模型OOM

### ISSUE THREAD

**Issue by qurikuduo** [thunlp/THUCTC#8]
我使用的数据集就是从网站上申请的 THUCNews  数据集，然后增加了一个分类，添加了一个分类“古文”文件夹，语料为大小25M的古代小说、诗词等。
使用的训练参数为： 
java -jar THUCTC_java_v1_run.jar -train /Users/xx/Documents/work/分类算法/THUCNews -s /Users/ss/Documents/work/分类算法/news_model -XX:PermSize=512m -XX:MaxPermSize=1024m -XX:-UseGCOverheadLimit -Xmx12000m -Xms14000m 

报错前的状态：
scanned 630001
scanned 640001
scanned 650001
scanned 660001
start chi-square calculation
store features...=======================================
5000
end store features...=======================================
generating feature map
feature selection complete
scanned 1
scanned 10001
scanned 20001

然后一直执行到下面报错：

报错为：

 scanned 550001
scanned 560001
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Integer.valueOf(Integer.java:832)
	at org.thunlp.text.classifiers.LiblinearTextClassifier.createLiblinearProblem(LiblinearTextClassifier.java:824)
	at org.thunlp.text.classifiers.LiblinearTextClassifier.train(LiblinearTextClassifier.java:757)
	at org.thunlp.text.classifiers.BasicTextClassifier.runAsBigramChineseTextClassifier(BasicTextClassifier.java:723)
	at org.thunlp.text.classifiers.BasicTextClassifier.main(BasicTextClassifier.java:806)
	... 5 more

请问需要继续调整jvm参数吗？有何建议，谢谢。

**Comment by qurikuduo** [comment]
在windows上，提供32G内存，没有再OOM了。
